### ISSUE TITLE
chr() arg not in range(0x110000)

### ISSUE THREAD

**Issue by StefaanVanDooren** [marcdjulien/spotify-terminal#86]
get this error when trying to run it on an iMac G4.

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/spotify-terminal.py", line 4, in <module>
    __import__('pkg_resources').run_script('spotify-terminal==0.15.2', 'spotify-terminal.py')
  File "/Users/Mac/Library/Python/3.8/lib/python/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/Mac/Library/Python/3.8/lib/python/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spotify_terminal-0.15.2-py3.8.egg/EGG-INFO/scripts/spotify-terminal.py", line 5, in <module>
    main()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spotify_terminal-0.15.2-py3.8.egg/spotify_terminal/main.py", line 97, in main
    api = ApiClass(args.username, args.use_cache)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spotify_terminal-0.15.2-py3.8.egg/spotify_terminal/api.py", line 124, in __init__
    self.auth = Authenticator(username)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spotify_terminal-0.15.2-py3.8.egg/spotify_terminal/authentication.py", line 46, in __init__
    self._init()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spotify_terminal-0.15.2-py3.8.egg/spotify_terminal/authentication.py", line 109, in _init
    line = "".join([
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spotify_terminal-0.15.2-py3.8.egg/spotify_terminal/authentication.py", line 110, in <listcomp>
    chr(i-1993) for i in struct.unpack("64I", f.readline())
ValueError: chr() arg not in range(0x110000)

**Comment by marcdjulien** [comment]
Most likely an issue with byte endianess. I'll try to fix this week.

**Comment by marcdjulien** [comment]
This is fixed now! Install the latest version (0.15.3).
